### ISSUE TITLE
Permission not overriding group entity limit from config

### ISSUE THREAD

**Issue by Baterka** [BentoBoxWorld/Limits#114]
**Description**
Permission not overriding group entity limit from config.

**Steps to reproduce the behavior:**
With setting:
```
entitygrouplimits:
  villagers:
    limit: 10
    entities:
      - VILLAGER
      - ZOMBIE_VILLAGER
```

and permission: `bskyblock.island.limit.villagers.20` for VIP players, those VIP players are still limited to 10...

**Expected behavior**
Permission should override default config.

**Server Information:**

[Please complete the following information:]
 - Database being used: MariaDB
 - OS: Debian 10
 - Java Version: 8
 - BentoBox version: 1.15.1
 - Addons installed? 
Biomes 1.13.0 (ENABLED)
BSkyBlock 1.14.0 (ENABLED)
Challenges 0.8.3 (ENABLED)
ControlPanel 1.7.0 (ENABLED)
DimensionalTrees 1.6.0 (ENABLED)
Level 2.5.0 (ENABLED)
Limits 1.15.0 (ENABLED)
Warps 1.10.0 (ENABLED)
