### ISSUE TITLE
Permissions its not work

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Limits#117]
**Screenshots**
![image](https://user-images.githubusercontent.com/47111280/101941645-555d3780-3bf9-11eb-9808-a3b7649c365e.png)
![image](https://user-images.githubusercontent.com/47111280/101941944-c866ae00-3bf9-11eb-98f8-f971936ae028.png)

But when try place villager, said "You cannot exceed the limit of 2."
![image](https://user-images.githubusercontent.com/47111280/101941812-935a5b80-3bf9-11eb-92e3-892a73a2cd7f.png)

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): JSON
 - OS: Centos 7
 - Java Version: 11
 - BentoBox version:
![image](https://user-images.githubusercontent.com/47111280/101941583-3e1e4a00-3bf9-11eb-9a0a-437b62f41588.png)

**Comment by tastybento** [comment]
<img width="378" alt="Screen Shot 2020-12-22 at 9 22 26 AM" src="https://user-images.githubusercontent.com/4407265/102915859-5848fb00-4437-11eb-92fa-5f54defdc3b0.png">
Hmm, I cannot replicate. 
```
> pex user LSPVicky
[09:23:46 INFO]: '0764d8a9-9461-4961-84c7-3bb4e2c7f9dd/LSPvicky' is a member of:
[09:23:46 INFO]:    default (not ranked)
[09:23:46 INFO]: LSPvicky's permissions:
[09:23:46 INFO]: 1) bskyblock.island.limit.villager.12 (own)
[09:23:46 INFO]: 2) essentials.* (own)
[09:23:46 INFO]: 3) essentials.spawnmob.* (own)
[09:23:46 INFO]: 4) essentials.summon (own)
[09:23:46 INFO]: 5) bukkit.summon (own)
[09:23:46 INFO]: LSPvicky's options:
[09:23:46 INFO]:   name = "LSPvicky"
```

Maybe there is another config file or permission interfering or taking precedent? Please share your Limits configs and all your perms.

**Comment by OverBrave** [comment]
![image](https://user-images.githubusercontent.com/47111280/102966939-f6a19300-4501-11eb-8610-04ec2d2fd235.png)


```
entitylimits:
  MINECART_CHEST: 5
  MINECART: 5
  IRON_GOLEM: 5
  CHICKEN: 30
  SHEEP: 30
  COW: 30
  MUSHROOM_COW: 15
  MINECART_HOPPER: 15
  SLIME: 5
  VINDICATOR: 15
  PHANTOM: 3
  ZOMBIE: 5
  CREEPER: 5
  SPIDER: 5
  SKELETON: 5
  ZOMBIFIED_PIGLIN: 5
  TURTLE: 5
  GUARDIAN: 5
  PUFFERFISH: 5
  COD: 5
  TROPICAL_FISH: 5
  SALMON: 5
  EVOKER: 5
  FOX: 5
  WITCH: 5
  ARMOR_STAND: 8
  ENDERMAN: 10
  HUSK: 15
  STRAY: 15
  POLAR_BEAR: 10
  BEE: 10
  ITEM_FRAME: 50
  DROWNED: 5
  ILLUSIONER: 5
  VILLAGER: 2
```
