### ISSUE TITLE
Placeholder %Limits_bskyblock_island_hopper_limit% not working

### ISSUE THREAD

**Issue by Jeroen123TC** [BentoBoxWorld/Limits#159]
### Expected behavior

The placeholder %Limits_bskyblock_island_hopper_limit% normally has a out put from the hopper limit out of the config.
```
blocklimits:
  HOPPER: 50
# This section is for world-specific limits and overrides the general limit
# Specify each world you want to limit individually (including nether and end worlds)
# If these worlds are not covered by the game modes above, nothing will happen
worlds:
  skyblock_world:
    HOPPER: 50
```
### Observed/Actual behavior

The placeholder %Limits_bskyblock_island_hopper_limit% has a output of "limit not set" see image
![image](https://user-images.githubusercontent.com/69977039/160125627-d2b1b933-d6d3-4e8b-b7aa-04a701979d56.png)

### Steps/models to reproduce

The placeholder %Limits_bskyblock_island_hopper_count% works fine so maybe that helps?

### BentoBox version

<img width="1520" alt="Schermafbeelding 2022-03-25 om 14 03 39" src="https://user-images.githubusercontent.com/69977039/160125900-5a5ab3fe-4ac7-41cb-80e8-e4b90f75dfde.png">
