### ISSUE TITLE
Locale file hit-limit messages

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Limits#33]
**Description**
When the limit of blocks or entities are reached, an error appears that the locale entry is missing
```
block-limits.hit-limit
entity-limits.hit-limit
```

**Steps to reproduce the behavior:**
1. Clean test server, with all latest plugins and add onss
2. Make an island
3. Place 11 hoppers
4. Place 11 chickens

**Expected behavior**
The locale file should be changed to:
```YAML
block-limits:
  hit-limit: "&c[material] limited to [number]!"
entity-limits:
  hit-limit: "&c[entity] spawning limited to [number]!"
limits:
  panel-title: "Island limits"
```
**or**
The code should use the default `limits.entity-hit-limit` and `limits.block-hit-limit`

**Screenshots**

**Server Information:**
Not important in this case, it's quite obvious
