### ISSUE TITLE
Critical: Too much nether monsters

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Limits#98]
**Description**
The problem is a bit too much monsters. There are approximately 600+ monsters on 1 island

For these mobs, I didn't set a limit. 
BSkyblock settings:
```yaml
  spawn-limits:
    # Spawn limits. These override the limits set in bukkit.yml
    # If set to a negative number, the server defaults will be used
    # Added since 1.11.2.
    monsters: -1
    # Added since 1.11.2.
    animals: -1
    # Added since 1.11.2.
    water-animals: -1
    # Added since 1.11.2.
    ambient: -1
```
So it should look for bukkit and the monsters from bukkit are 24. This is clearly more that 24.
I think is related to other limits issues. (Infinite bee's, slimes) But I'm not sure.

**Steps to reproduce the behavior:**
1. Go to the nether
2. Check to see how many mobs there are of an unlimited kind of mob

**Expected behavior**
Normal mob spawning behavior

**Screenshots**
![2020-09-11_22 11 07](https://user-images.githubusercontent.com/28690790/92969014-653f7100-f47c-11ea-9aac-67e928c3f373.png)

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): [JSON]
 - OS: [Linux]
 - Java Version: [Java 11]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
```yaml
Running Invalid (PURPUR) 1.16.1.
BentoBox version: 1.15.1-SNAPSHOT-b1869
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
Loaded Addons:
Biomes 1.13.0 (ENABLED)
BSkyBlock 1.14.1-SNAPSHOT-b673 (ENABLED)
Challenges 0.8.4-SNAPSHOT-b428 (ENABLED)
Level 2.4.1 (ENABLED)
Limits 1.15.0-SNAPSHOT-b231 (ENABLED)
MagicCobblestoneGenerator 2.2.0-SNAPSHOT-b160 (ENABLED)
Warps 1.10.1-SNAPSHOT-b267 (ENABLED)
```
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Additional context**
